### ISSUE TITLE
is_probable_prime

### ISSUE THREAD

**Issue by dsernst** [juanelas/bigint-mod-arith#5]
This is awesome 👏

Are you open to adding a `is_probable_prime(num_rounds)` method using the [Miller-Rabin Primality test](https://en.wikipedia.org/wiki/Miller–Rabin_primality_test)?

**Comment by juanelas** [comment]
Sorry to reply that late!
I created that functionality in another repository (that depends on this one) some years ago. Check if this meets your needs: [https://github.com/juanelas/bigint-crypto-utils/blob/master/docs/API.md#isprobablyprime](https://github.com/juanelas/bigint-crypto-utils/blob/master/docs/API.md#isprobablyprime)
The only difference is that, before running Miller-Rabin, it first tries if any of the first 250 small primes are a factor of the input number. Based on my tests (and some others' advice), this initial testing likely helps running the test faster.

**Comment by dsernst** [comment]
Ooo amazing!
